### ISSUE TITLE
Wrong result from "RRule.fromString"

### ISSUE THREAD

**Issue by mmestani** [waratuman/rfc5545-rrule#3]
Tried an example and got a wrong result (check `byYearDay` in the result in the code below):

**Text**: _every 3 years on the 1st, 100th and 240th day for 10 times_
**RRULE**: `RRULE:FREQ=YEARLY;INTERVAL=3;COUNT=10;BYYEARDAY=1,100,240`

Source Code: 

```
let { RRule, Day } = require('rfc5545-rrule');

let rrule = RRule.fromString(
  'RRULE:FREQ=YEARLY;INTERVAL=3;COUNT=10;BYYEARDAY=1,100,240'
);

console.log(rrule);
// RRule {
//  interval: 3,
//  bySecond: [],
//  byMinute: [],
//  byHour: [],
//  byDay: [],
//  byMonthDay: [],
//  byYearDay: [ 1, 10, 24 ], // TODO it should have been [1, 100, 240]
//  byWeekNumber: [],
//  byMonth: [],
//  bySetPosition: [],
//  weekStart: 1,
//  toJSON: [Function (anonymous)],
//  frequency: 'yearly',
//  count: 10
// }
```

Generating the RRULE using `new RRule` works fine
```
let newRRule = new RRule({
  frequency: 'yearly',
  interval: 3,
  byYearDay: [1, 100, 240],
  count: 10
});

console.log(newRRule.toString());
// RRULE:FREQ=YEARLY;COUNT=10;INTERVAL=3;BYYEARDAY=1,100,240
```

**Comment by mmestani** [comment]
@waratuman

**Comment by waratuman** [comment]
@mmestani I've just pushed a fix for this. Can you confirm that it works.

**Comment by mmestani** [comment]
> @mmestani I've just pushed a fix for this. Can you confirm that it works.

@waratuman - It works properly now, Thank you for the quick fix. Closing the issue.. 🚀
